name = "MomentDistances"
uuid = "6d79b445-47d2-435a-955a-fbe0d268cddb"
version = "0.1.2"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
ArgCheck = "1, 2"
DocStringExtensions = "0.8, 0.9"
julia = "1.10"
